package com.kazumaproject.data.symbol

data class Symbol(val symbol: String, val category: SymbolCategory)

enum class SymbolCategory {
    BRACKETS_AND_QUOTES, PUNCTUATION_AND_DIACRITICS, Hankaku, GENERAL, ARROWS,
    MATH_AND_UNITS, GEOMETRIC_SHAPES, ALPHABET_LATIN, ALPHABET_GREEK,
    ALPHABET_CYRILLIC, BOX_DRAWING, PICTOGRAPHS_AND_ICONS, ROMAN_NUMERALS,
    ENCLOSED_CHARACTERS, PHONETIC_SYMBOLS, JAPANESE_KANA_AND_VARIANTS,
    CJK_AND_RADICALS, CONTROL_CHARACTERS
}
